.github/workflows/windows.yml, CMakeLists.txt, scripts/ci/install_cuda_windows.ps1, src/3rd_party/half_float/umHalf.inl, src/CMakeLists.txt, src/data/sentencepiece_vocab.cpp, src/data/sentencepiece_vocab.h, src/data/types.h, src/data/vocab.cpp, src/data/vocab.h, src/data/vocab_base.h, src/tests/CMakeLists.txt, src/tests/sentencepiece_norm.cpp
The following is what's essentially getting added.
```cpp
void SentencePieceVocab::encodeAsSentencePieceText(const std::string& line,
sentencepiece::SentencePieceText& spt) const {
spm_->Encode(line, &spt);
}
```
But I need compiler to know `SentencePieceVocab` for using `tryAs` for more than `FactoredVocab`:
```cpp
sentencepiece::SentencePieceText Tokenizer::tokenize(std::string const &snt) {
// TODO(jerin): Bunch of hardcode here, 1, 0, need to get rid off somehow.
auto vImpl = vocabs_[0]->tryAs<marian::SentencePieceVocab>();
sentencepiece::SentencePieceText spt;
vImpl->encodeAsSentencePieceText(snt, spt);
return spt;
}
```
Therefore `sentencepiece_vocab.cpp` -> `sentencepiece_vocab.h` + `sentencepiece_vocab.cpp`.
=> SentencePiece enhancements for Bergamot

.gitmodules
It caused issues in CircleCI, see https://github.com/mozilla/bergamot-translator/pull/1#issuecomment-781876515
=> Remove trailing slash from intgemm submodule gitmodules config

src/data/sentencepiece_vocab.cpp, src/data/vocab.cpp, src/data/vocab.h, src/data/vocab_base.h, src/tests/sentencepiece_norm.cpp
Attempting to solve https://github.com/browsermt/bergamot-translator/issues/25. Might be useful for https://github.com/marian-nmt/marian-dev/issues/775 (?)
Changes test to accommodate the decoded string_views as well. The square-brackets indicate annotations using string_views, constructed by [src/tests/sentencepiece_norm.cpp](https://github.com/browsermt/marian-dev/blob/9d5d0d74ffbbfcd9cdfe097f9dfe9e46d929ef86/src/tests/sentencepiece_norm.cpp). The test previously for `encodeWithByteRanges` is modified to include `decodeWithByteRanges` as well. Once the expected is set to the output, this regression-tests can be modified as well.
<details>
<summary>Input Text </summary>
```
Äffin
Henry IV
Ç
가
ℌℍ
①
︷
i⁹
¼
```
</details>
<details>
<summary>Output </summary>
<p>
```
Original: [Ä][ff][in] …
```
=> Adding decodeWithByteRanges: string_views into translated-text

CHANGELOG.md, src/CMakeLists.txt, src/command/marian_conv.cpp, src/common/hash.h, src/data/shortlist.cpp, src/data/shortlist.h, src/translator/translator.h
This PR adds a new binary shortlist generator which allows the decoder to load a lexical shortlist from a binary blob. 
It is related to issues: #19 
- Add `BinaryShortlistGenerator` Class to load lexical shortlist from a binary blob.
To use a binary shortlist, you should provide the file path and whether the file needs checking (optional; true by default). 
For example:
```
--shortlist lex.esen.bin false
``` 
- Add a shortlist converter which can convert a text lexical shortlist to a binary shortlist. This converter is integrated into `marian-conv` with `--shortlist,-s` option
Shortlist conversion usage example:
```
./marian-conv --shortlist lex.esen.s2t 100 100 0 \
--dump lex.esen.bin \
--vocabs vocab.esen.spm vocab.esen.spm
```
- Update Marian decoder with an option of …
=> Add binary shortlist and converter

.github/workflows/native-customized_marian-macos.yml, .github/workflows/wasm-customized_marian-macos.yml, .github/workflows/wasm-customized_marian-ubuntu.yml, CHANGELOG.md, CMakeLists.txt, src/3rd_party/CMakeLists.txt, src/CMakeLists.txt, wasm/Makefile, wasm/README.md
Compiling to wasm platform for inference requires only a subset of marian sources. This PR introduces the ability to compile these sources to native platform as well.
Motivation of this change?
Doing this enables debugging the wasm runtime failures by first reproducing the same failures on native platform with the native binaries built using the same sources that were used to build wasm binary. In the past, this has proven to be useful where we could quickly diagnose a few wasm specific issues (e.g. `size_t` inconsistency).
- Encapsulate all wasm compatible sources under a single cmake option
- Added a github workflow to compile these wasm compatible sources natively as well
=> Enable compiling wasm compatible marian sources natively

.github/workflows/native-customized_marian-macos.yml, .github/workflows/wasm-customized_marian-macos.yml, .github/workflows/wasm-customized_marian-ubuntu.yml, CMakeLists.txt, src/3rd_party/CMakeLists.txt, src/3rd_party/cnpy/cnpy.h, src/3rd_party/pathie-cpp/src/path.cpp, src/CMakeLists.txt, src/common/file_stream.cpp, src/common/file_stream.h, src/common/logging.cpp, src/functional/operators.h, src/graph/node_initializers.cpp, src/layers/generic.cpp, src/layers/lsh.h, wasm/Makefile, wasm/README.md
This PR improves the names of cmake options (and corresponding compile definitions set by them) that are specific to wasm platform.
- Renamed `USE_WASM_COMPATIBLE_MARIAN` cmake option to `USE_WASM_COMPATIBLE_SOURCE` as per [agreement](https://github.com/browsermt/bergamot-translator/pull/74#issuecomment-811091459)
- This cmake option is used to enable a subset of marian sources that compile to wasm
- Use `WASM_COMPATIBLE_SOURCE` compile definition at all places where `WASM` compile definition was wrongly used
This PR doesn't add/modify/remove any functionality. Therefore, I didn't update the CHANGELOG.md. Please let me know if I still need to update it.
=> Cmake option and preprocessor cleanup for wasm platform

.github/workflows/macos.yml, .github/workflows/ubuntu.yml
The PR fixes the CI failures happened because of recent changes in Github builders.
=> Fixing Mac and Ubuntu CI failures

CMakeLists.txt
Upgrades the minimum required cmake version to 3.12.4
This PR is related to the issue: https://github.com/browsermt/marian-dev/issues/33
=> Upgrade cmake_minimum_required to 3.12.4

CHANGELOG.md, src/data/default_vocab.cpp, src/data/factored_vocab.h, src/data/sentencepiece_vocab.cpp, src/data/vocab.cpp, src/data/vocab.h, src/data/vocab_base.h
This PR enables loading SentencePiece vocabs from the buffer which is required in bergamot-translator.
It is related to https://github.com/browsermt/bergamot-translator/pull/122
- Add `loadFromSerialized()` in `data/vocab.h`, `data/vocab_base.h `, `data/vocab.cpp` and `data/default_vocab.cpp`.
- Implement `loadFromSerialized()` in `data/sentencepiece_vocab.cpp`
=> Enable binary vocab loading from buffer

CHANGELOG.md, src/common/config_parser.cpp, src/common/config_validator.cpp, src/common/io.cpp, src/common/io.h, src/graph/expression_graph.h, src/models/amun.h, src/models/costs.h, src/models/encoder_decoder.cpp, src/models/encoder_decoder.h, src/models/nematus.h, src/translator/scorers.cpp, src/translator/scorers.h, src/translator/translator.h
Commits rebased from marian-nmt#860. Instead of loading each model twice per thread, it loads the model once. 
**Note: this PR adds a CLI option for MMAP (consistent with upstream) but is off by default - this shouldn't interfere with the changes to disable MMAP in this repository.**
- Adds `--model-mmap` as a command line option (uses mio)
- Preloads model to Item vector before creating scorers
- try-catch when loading model YAML is replaced with if-else
- Extended `IEncoderDecoder` to load from Item vector
- `Amun` and `Nematus` models load overload for Item vector
Describe how to test your changes, adding command line examples and sample input/output files if relevant.
Point to unit tests or regression tests covering the changes if they have …
=> Scorer model loading

src/data/shortlist.cpp
The generation of the shortlist requires the size of the vocabulary. Before the modification, the size is measured following the legacy LexicalShortlistGenerator. However, it gives the wrong size when (max source word ID) < (vocabulary size - 1). And the program crashes (@jelmervdl Thanks for pointing out). The modification retrieves the size directly to avoid such a problem and to avoid resizing.
=> Fix binary shortlist to use vocab size

.github/workflows/wasm-customized_marian-macos.yml, .github/workflows/wasm-customized_marian-ubuntu.yml, CMakeLists.txt, src/3rd_party/CMakeLists.txt
The PR enables running wasm port on browsers that don't enable SharedArrayBuffer. Detailed reasoning explained here: https://github.com/mozilla/bergamot-translator/issues/63
Fixes https://github.com/browsermt/marian-dev/issues/53
- Compile without `-pthreads` compilation flag for wasm
- Disable building sentencepiece executables for wasm builds (only libraries are required for wasm)
- Changed emsdk version in wasm specific github workflows to make it consistent across marian and bergamot-translator (see [here](https://github.com/browsermt/bergamot-translator/blob/main/.circleci/config.yml#L5))
=> Wasm builds without SharedArrayBuffer

wasm/import-gemm-module.js, wasm/package-benchmark.sh
Fixes a part of https://github.com/browsermt/bergamot-translator/issues/264 and the rest of https://github.com/browsermt/marian-dev/issues/63 as per https://github.com/browsermt/marian-dev/pull/64#issuecomment-970180351
- Added file `wasm/import-gemm-module.js` that houses the logic to import the optimized gemm when available, otherwise fallback gemm
Follow [README](https://github.com/browsermt/marian-dev/tree/master/wasm#readme) and do the inference in the browser console. The optimized gemm is called when run on locally compiled version of firefox browser that exports a dummy implementation for gemm intrinsics. This proves that the logic written here works correctly.
=> Import optimized gemm implementation when available for wasm target

CHANGELOG.md, cmake/FindSSE.cmake
Update AVX2 detection script to properly support macOS
This is a fix for Marian's FindSSE.cmake script: https://github.com/marian-nmt/marian-dev/issues/880
- also queries machdep.cpu.leaf7_features on macOS when searching for CPU features
```
mkdir build
cd build
cmake .. | fgrep AVX2
```
=> Fix AVX2 detection on macOS

src/tensors/cpu/integer_common.h
Fixes #72.
I presume this helps the compiler with realising that the condition doesn't change, and allows it to unroll/optimise it much better.
=> Replace "dynamic" loop condition with const variable

src/tensors/cpu/intgemm_interface.h
This fixes a bug when switching between translation models that have different `gemm-precision` precisions specified in their configuration file. Which is why we never noticed it with our own student models (all `int8shiftAlpha`), but do see it now with the Ukrainian model (which uses just `int8`)
I tried to go through git blame to figure out why it was marked `static`.  @XapaJIaMnu please correct me if I'm wrong.
1. It was introduced in b75168dcc826ff0a74fac6d74ad067fc9fa977bc. Probably as an optimisation?
2. Then in 2b9e69dbb3f9d7a4c4d05269c9a4492cf49ec01b the other static variable, `static auto map = b->graph()->params()->getMap();` in `fetchAlphaFromModel(Expr b)` disappears when that function is rewritten into a `UnaryNodeOp`. But the one removed in this pull request remained.
=> Remove `static` precomputedAlphas bool in `affine` operation

src/tensors/cpu/intgemm_interface.h
This PR is hopefully a fix for https://github.com/XapaJIaMnu/translateLocally/issues/88. 
- Removed dereference of vector end iterator
- Copies of IntrusivePtr avoids access errors
This needs further investigation to understand what is going on with memory on windows. As @XapaJIaMnu says in a comment on the linked issue
> Something is very weird.
Ran on Windows.
=> Quick fix for Windows issues

src/tensors/cpu/wasm_intgemm_fallback.cpp
This fixes base student models not working with the wasm version of bergamot-translator.
`int8PrepareBias` is being called from both [`PrepareBiasForBNodeOp`](https://github.com/browsermt/marian-dev/blob/53c4f7e4537dbf7782c583e98f50e513f0a27541/src/tensors/cpu/intgemm_interface.h#L349) and [`PrepareFakeBiasForBNodeOp`](https://github.com/browsermt/marian-dev/blob/53c4f7e4537dbf7782c583e98f50e513f0a27541/src/tensors/cpu/intgemm_interface.h#L386). These are two different intgemm calls (callbacks differ) but they map to the same WASM surrogate function.
I'm using the fact that one of those calls has `bias_input = nullptr` as a way to differentiate between the two and call the correct intgemm function + callback pair in its implementation.
This will also need to be fixed in Mozilla's tree, …
=> Patch int8PrepareBias to handle nullptr

src/training/communicator.h
Remove unused variable that the version of clang 13.1.6 (clang-1316.0.21.2) that XCode 13.3 ships with picks up on. Our compiler flags don't allow this.
```
marian-dev/src/training/communicator.h:105:11: error: variable 'pos' set but not used [-Werror,-Wunused-but-set-variable]
int pos = 0;
^
```
I have not test training after this change.
I assume it is safe since the variable is a simple scalar, is only ever written to, and those writing statements all involve only scalars. So I don't expect any side effects suddenly being different.
=> Remove unused variable

.github/workflows/wasm-customized_marian-macos.yml, .github/workflows/wasm-customized_marian-ubuntu.yml, CHANGELOG.md, CMakeLists.txt, wasm/Dockerfile, wasm/README.md
Fixes https://github.com/browsermt/marian-dev/issues/89
- Upgrade emsdk version from 2.0.9 to 3.1.8
- Updated cmake files to follow strict separation b/w compile and link flags
Followed [README](https://github.com/browsermt/marian-dev/tree/master/wasm#readme) instructions to run marian-decoder executable in Firefox browser to see translations in console logs.
@jelmervdl Thanks for inspiring this change.
=> Upgrade emsdk
